### ISSUE TITLE
Move or replicate the Edit Posting JSON Metadata button to the top of the block.

### ISSUE THREAD

**Issue by brianoflondon** [ausbitbank/hive.ausbit.dev-src#9]
Love it! One request: I'll try to make this in Github too.

Can you move the edit button to the TOP of the post-metadata-json block? I have a huge dump of RSS feed in mine, makes scrolling through it a pain. Perhaps you could also hide very large json objects?

**Comment by ausbitbank** [comment]
Done! And for bonus points there's also an anchor to scroll the page as well https://hive.ausbit.dev/@brianoflondon#posting_meta
